### ISSUE TITLE
[Question] Vanadium autofill support

### ISSUE THREAD

**Issue by Ilithy** [mathfactory/mooltifill-android#2]
Hi;
I would like to know if mooltifill-android supports autofill in Vanadium browser?

[Vanadium link](https://github.com/GrapheneOS/Vanadium)  (project derived from [GrapheneOS](https://github.com/GrapheneOS) )

Thank you in advance.

**Comment by Ilithy** [comment]
I'm answering my own question, no mooltifill does not manage autofill on the Vanadium browser (nor on any other browser tested, except Firefox)

**Comment by mathfactory** [comment]
@Ilithy Vanadium can probably be included in the list of browsers in: https://github.com/mathfactory/mooltifill-android/blob/master/app/src/main/res/xml-v28/autofill_service.xml

If you find out the package name(s) to be included, you can start a PR for this file (or let me add it). In this case, please reopen this issue to track the progress of vanadium support.

**Comment by Ilithy** [comment]
@mathfactory That's kind of you,
but the package is normally already supported (org.chromium.chrome), but it doesn't work, I don't think much can be done to fix this, that's why I closed this.
_(by the way, bromite is noted, but the autofill does not work with it on my pixel 6 pro under grapheneOS, except for the connection to github surprisingly)_.

Thanks again.
